[package]
version = "1.1.5"
category = "Simulation"
title = "Ros2 Robot Description URDF Importer"
description = "This extensions expands the URDF Importer by enabling importing the robot description from a given ROS node"
keywords = ["isaac", "ROS2", "URDF"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.ros2.urdf."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.ros2.urdf" = {}

[[python.module]]
name = "omni.isaac.ros2_bridge.robot_description"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
