[package]
version = "8.0.7"
category = "Simulation"
title = "Isaac Sim Motion Generation"
description = "Extension that provides support for generating motion with Lula-based motion policies and an interface for writing arbitrary motion policies"
keywords = ["isaac", "motion generation", "lula", "motion policy"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot_motion.motion_generation"

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot_motion.motion_generation" = {}

[[python.module]]
name = "omni.isaac.motion_generation"

[[python.module]]
name = "omni.isaac.motion_generation.tests"

[[test]]
dependencies = [
   "omni.isaac.core",
   "omni.isaac.nucleus",
]
