[package]
version = "2.0.8"
category = "Simulation"
title = "Robot Assembler"
description = "Alpha version of Robot Assembler Extension: Assemble multiple Articulations into a single robot"
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot_setup.assembler."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot_setup.assembler" = {}

[[python.module]]
name = "omni.isaac.robot_assembler.tests"

[[test]]
dependencies = [
    "omni.isaac.core",
    "omni.isaac.nucleus"
]
