[package]
version = "2.0.7"
category = "Simulation"
title = "Isaac Sim Proximity Sensor Example"
description = "Extension that provides a proximity sensor example"
keywords = ["isaac", "lula", "rmp"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.sensors.physx."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.sensors.physx" = {}

[[python.module]]
name = "omni.isaac.proximity_sensor"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
