[package]
version = "2.0.8"
category = "Simulation"
title = "Occupancy Map Generator"
description = "Generate occupancy maps"
keywords = ["isaac", "block world"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.asset.gen.omap" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.occupancy_map"

[[python.module]]
name = "omni.isaac.occupancy_map.tests"

[[test]]
dependencies = [
    "omni.isaac.core",
    "omni.isaac.nucleus",
]
