[package]
version = "3.0.7"
category = "Simulation"
title = "Isaac Quadruped Robot"
description = "Simulation for legged robots"
keywords = ["isaac", "robot", "quadruped"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. The built in optimization controller will be removed. The RL based controller will be replaced by isaacsim.robot.policy.examples"

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot.policy.examples" = {}

[[python.module]]
name = "omni.isaac.quadruped"

[[python.module]]
name = "omni.isaac.quadruped.tests"

[[test]]
dependencies = [
   "omni.isaac.core",
]

args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
