[package]
version = "2.0.6"
category = "Simulation"
title = "Isaac Sim Range Sensor Examples"
description = "Examples for the Range Sensor extension"
keywords = ["isaac", "physics", "sensor", "lidar", "examples"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.sensors.physx.examples."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.sensors.physx.examples" = {}

[[python.module]]
name = "omni.isaac.range_sensor.examples"

[[python.module]]
name = "omni.isaac.range_sensor.examples.lidar_info"

[[python.module]]
name = "omni.isaac.range_sensor.examples.generic_info"

[[test]]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
