[package]
version = "4.0.6"
category = "Simulation"
title = "Isaac Sim Range Sensor"
description = "Range based sensor simulation using physx"
keywords = ["isaac", "physics", "sensor", "lidar"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.sensors.physx."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.sensors.physx" = {}

[[python.module]]
name = "omni.isaac.range_sensor"

[[python.module]]
name = "omni.isaac.range_sensor.tests"

[[test]]
dependencies = [
   "omni.isaac.core",
   "omni.isaac.nucleus"
]
args = [
'--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]

[[test]]
name = "startup"
args = [
    '--/app/settings/fabricDefaultStageFrameHistoryCount = 3',
]
