[package]
version = "2.0.8"
category = "Simulation"
title = "UI components for the Isaac Sim Occupancy Map"
description = "2D Occupancy Map Generation"
keywords = ["isaac", "occupancy map"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[dependencies]
"isaacsim.asset.gen.omap.ui" = {}
"isaacsim.core.deprecation_manager" = {}

[[python.module]]
name = "omni.isaac.occupancy_map.ui"

[[python.module]]
name = "omni.isaac.occupancy_map.ui.tests"
