[package]
version = "1.0.6"
category = "Simulation"
title = "Scene Blox"
description = "A package to buid scenes for Omniverse"
keywords = ["isaac", "omniverse", "scene blox"]
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.replicator.scene_blox."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.replicator.scene_blox" = {}

[[python.module]]
name = "omni.isaac.scene_blox"
