[package]
version = "1.0.5"
category = "Simulation"
title = "Isaac Sim Physics Utilities"
description = "Collision and Physics Utils"
keywords = ["isaac", "physics", "utils",]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.util.physics."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.util.physics" = {}

[[python.module]]
name = "omni.isaac.physics_utilities"
