[package]
version = "3.0.5"
category = "Simulation"
title = "Robot Description Editor"
description = "Generates and edit Lula robot_description YAML files"
keywords = ["isaac", "collision spheres", "lula", "robot description"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[deprecation]
warning = "Extension deprecated since Isaac Sim 4.5.0. Replaced by isaacsim.robot_setup.xrdf_editor."

[dependencies]
"isaacsim.core.deprecation_manager" = {}
"isaacsim.robot_setup.xrdf_editor" = {}
